<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>RobbyCopy</AssemblyName>
    <RootNamespace>RobbyCopy</RootNamespace>
    <LangVersion>latest</LangVersion>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationIcon>robben.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="robben.png" />
  </ItemGroup>

</Project>
